version: "3"

# 声明一个名为network的networks,subnet为network的子网地址,默认网关是172.8.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '172.8.0.0/16'
# 配置各个服务
services:
  # lunabot本体
  nonebot:
    # 从本地的dockerfile构建镜像
    build:
      context: ./lunabot_nonebot
      dockerfile: ./Dockerfile
    # 容器名称
    container_name: lunabot-nonebot
    restart: always
    # 配置端口映射，本地的端口多加一位防止和本地的程序冲突
    ports:
      - '18383:8383'
      - '18486:8486'
    # 配置容器在network中的ip地址
    networks:
      network:
        ipv4_address: 172.8.0.11
    # 配置挂载卷
    volumes:
      - ./data:/app/lunabot_nonebot/data # 必须和napcat、deck-recommend挂载到同一个位置
      - ./lunabot_nonebot/config:/app/lunabot_nonebot/config # 配置docker的config
  
  # 配置napcat 如果你本身就有了napcat，可以将那个napcat关掉
  # 然后将volume中的/app/.config/QQ和/app/napcat/config挂载到原来那个napcat的位置上
  napcat:
    # 使用napcat官方镜像
    image: mlikiowa/napcat-docker:latest
    container_name: lunabot-napcat
    restart: always
    ports:
      - '13000:3000'
      - '13001:3001'
      - '16099:6099'
    networks:
      network:
        ipv4_address: 172.8.0.12
    # 环境，不清楚这是什么，官方是这么写的
    # 需要在docker compose命令前加上 NAPCAT_UID=$(id -u) NAPCAT_GID=$(id -g) 
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
    volumes:
      - ./napcat/QQ:/app/.config/QQ
      - ./napcat/config:/app/napcat/config
      - ./data:/app/lunabot_nonebot/data # 必须和nonebot挂载到同一位置
  
  # 配置后端服务，建议将gameapi和assets的服务分开
  # 可以使用haruki的开源项目
  # 我这里这个服务只是单纯的转发，没有什么功能
  # 所以就随便放一起了，且没有配置数据库
  server:
    build:
      context: ./lunabot_server
      dockerfile: ./Dockerfile
    container_name: lunabot-server
    restart: always
    ports:
      - '18888:8888'
    # 如果你有配置数据库，在这里等待数据库启动完毕之后再启动，避免不必要的连接失败
    depends_on:
      pgsql:
        condition: service_healthy
    #   redis:
    #     condition: service_healthy
    networks:
      network:
        ipv4_address: 172.8.0.13
    
  # 配置组卡服务
  deck-recommender:
    build: 
      context: ./deck_recommender
      dockerfile: ./Dockerfile
    # image: deck-recommender:latest
    container_name: deck-recommender
    restart: always
    ports:
      - '15556:45556'
    networks:
      network:
        ipv4_address: 172.8.0.14
    volumes:
      - ./data/sekai/deckrec:/app/deck_recommender/data/sekai/deckrec # 必须和nonebot挂载到同一位置
  
    # pgsql数据库
  pgsql:
    image: postgres:18-alpine
    container_name: lunabot-pgsql
    restart: always
    environment:
      # 配置要和config.docker.yaml中一致
      # 在生产环境中，请将username和password修改掉
      POSTGRES_USER: lunabot           # 设置超级用户用户名
      POSTGRES_PASSWORD: lunabot  # 设置超级用户密码
      POSTGRES_DB: lunabot      # 设置初始创建的数据库名
    healthcheck:
      # pg_isready 是官方自带的工具，无需额外安装
      # -U 指定用户名，-d 指定数据库（提高准确性）
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s      # 每 10 秒检查一次
      timeout: 5s       # 每次检查超过 5 秒视为超时
      retries: 5        # 连续失败 5 次后标记为 unhealthy
      start_period: 10s # 容器启动后的前 10 秒不计入失败次数（给数据库启动时间）
    ports:
      - "15432:5432"
    volumes:
      - ./data/pgsql:/var/lib/postgresql
    networks:
      network:
        ipv4_address: 172.8.0.21

  # autochat服务，这一项是可选的，如果你不需要autochat服务可以将这一项注释掉
  autochat:
    build:
      context: ./autochat
      dockerfile: ./Dockerfile
    container_name: lunabot-autochat
    restart: always
    # ports: # 这个服务没有开放端口
    networks:
      network:
        ipv4_address: 172.8.0.16
    volumes:
      - ./lunabot_autochat/config:/app/lunabot_autochat/config
      - ./data:/app/lunabot_autochat/data # 总之是同一个data
  # event-tracker服务，也是可选的
  event-tracker:
    build:
      context: ./event_tracker
      dockerfile: ./Dockerfile
    container_name: lunabot-event-tracker
    restart: always
    # ports: # 这个服务没有开放端口
    networks:
      network:
        ipv4_address: 172.8.0.17
    volumes:
      - ./event_tracker/config:/app/lunabot_event_tracker/config
      - ./data:/app/lunabot_event_tracker/data # 总之是同一个data

