[project]
name = "autochat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiorpcx>=0.25.0",
    "chromadb>=1.3.7",
    "orjson>=3.11.5",
    "setproctitle>=1.3.7",
    "websockets>=15.0.1",
]

# 配置镜像源
[[tool.uv.index]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple"
default = true
