service_name: "lunabot-event-tracker"

data_dir: "/app/lunabot_event_tracker/data"

log_level: "INFO"

api_base_path: "http://server:8888"

request_timeout: 5.0

regions: [ 'jp', 'cn' ]

sk:
  record_interval_seconds: 300
  high_res_record:  # 高精度榜线记录
    interval_seconds: 10
    ranks:  # 应用高精度的排名档位范围
      jp: []
    uids:   # 应用高精度的uid列表
      jp: []
  record_interval_tolerance: 70  # 超过该容差认为有记录丢失

  plot_point_num_limit: 5000

  record_time_after_event_end_minutes: 0
  update_ranking_log_interval: 30
  csb_judge_stop_threshold_minutes: 5